//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Soytur1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GirisTablosu
    {
        public int id { get; set; }
        public string KullaniciAdi { get; set; }
        public string MailAdres { get; set; }
        public string Sifre { get; set; }
    }
}
